# Generated by Django 2.1.4 on 2018-12-14 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerifyRecord',
        ),
    ]
