# Generated by Django 2.1.4 on 2018-12-14 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20181214_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passedcourse',
            options={'verbose_name': '通过题目', 'verbose_name_plural': '通过题目'},
        ),
        migrations.AlterModelOptions(
            name='publishedcourse',
            options={'verbose_name': '发布题目', 'verbose_name_plural': '发布题目'},
        ),
    ]
