# Generated by Django 2.1.4 on 2018-12-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20181214_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseresource',
            name='download',
        ),
    ]
