# Generated by Django 2.1.4 on 2018-12-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20181220_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonresource',
            name='download',
            field=models.FileField(upload_to='resource/%Y/%m/%d', verbose_name='资源文件'),
        ),
    ]
