# Generated by Django 2.1.4 on 2019-03-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessondetail',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='课节名'),
            preserve_default=False,
        ),
    ]
