# Generated by Django 2.1.4 on 2018-12-14 03:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_emailverifyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.TextField(default=b'\x80\x03]q\x00}q\x01a.', verbose_name='通过题目')),
            ],
        ),
        migrations.CreateModel(
            name='PublishedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.TextField(default=b'\x80\x03]q\x00}q\x01a.', verbose_name='发布题目')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='passed_problem',
        ),
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='老师'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更改时间'),
        ),
        migrations.AddField(
            model_name='publishedcourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='passedcourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户'),
        ),
    ]
