# Generated by Django 2.1.4 on 2018-12-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20181218_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='avatar/default.png', upload_to='avatar/%Y%m%d'),
        ),
    ]
