# Generated by Django 2.1.4 on 2019-03-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190303_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.TextField(default='暂时没有描述信息', verbose_name='描述信息'),
        ),
    ]
