# Generated by Django 2.1.4 on 2019-03-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishedcourse',
            name='user',
        ),
        migrations.DeleteModel(
            name='PublishedCourse',
        ),
    ]
