# Generated by Django 2.1.4 on 2018-12-19 13:43

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20181219_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessondetail',
            name='detail',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='课程内容'),
        ),
    ]
