# Generated by Django 2.1.4 on 2018-12-20 00:11

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20181220_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessondetail',
            name='detail',
            field=DjangoUeditor.models.UEditorField(verbose_name='课程内容'),
        ),
    ]
