# Generated by Django 2.1.4 on 2018-12-19 23:57

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20181219_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=DjangoUeditor.models.UEditorField(verbose_name='课程描述'),
        ),
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=DjangoUeditor.models.UEditorField(verbose_name='课程详情'),
        ),
        migrations.AlterField(
            model_name='course',
            name='required_knowledge',
            field=DjangoUeditor.models.UEditorField(default=b'\x80\x03]q\x00}q\x01a.', verbose_name='预备知识'),
        ),
        migrations.AlterField(
            model_name='lessonnode',
            name='note',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='笔记内容'),
        ),
    ]
