# Generated by Django 2.1.4 on 2018-12-20 00:57

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20181219_1930'),
        ('course', '0010_auto_20181220_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', DjangoUeditor.models.UEditorField(default='', verbose_name='笔记内容')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更改时间')),
            ],
            options={
                'verbose_name': '笔记内容',
                'verbose_name_plural': '笔记内容',
            },
        ),
        migrations.RemoveField(
            model_name='lessonnode',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='lessonnode',
            name='user',
        ),
        migrations.RenameField(
            model_name='lessonresource',
            old_name='course',
            new_name='lesson',
        ),
        migrations.AddField(
            model_name='course',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更改时间'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更改时间'),
        ),
        migrations.AddField(
            model_name='lessondetail',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='lessondetail',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更改时间'),
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更改时间'),
        ),
        migrations.DeleteModel(
            name='LessonNode',
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Lesson', verbose_name='章节'),
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户'),
        ),
    ]
